<a href="https://colab.research.google.com/github/kavya2299/Pytorch/blob/master/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [0]:
# uninitialized matrix
x = torch.empty(5, 3)
print(x)
# random initialization
x = torch.rand(5, 3)
print(x)
# zero initialization
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
# values initialization
x = torch.tensor([5.5, 3, 7, 98])
print(x)

tensor([[7.1079e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])
tensor([[0.4345, 0.2770, 0.0935],
        [0.2348, 0.0703, 0.0806],
        [0.7266, 0.6007, 0.1692],
        [0.3602, 0.0144, 0.9920],
        [0.4022, 0.5477, 0.3322]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([ 5.5000,  3.0000,  7.0000, 98.0000])


In [0]:
# unity initialization
x = x.new_ones(5, 3, dtype=torch.int)      # new_* methods take in sizes
print(x)
# to get the size of a matrix x
print(x.size())
# to override only the data type and leaving the values and size constant
x = torch.randn_like(x, dtype=torch.float)    
print(x)                                      
print(x.size())

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.Size([5, 3])
tensor([[ 0.5422,  0.3284,  0.6892],
        [ 1.3852, -0.2142,  1.3812],
        [ 0.7038, -0.3737, -2.2642],
        [ 0.2268,  1.0112, -2.3018],
        [-0.8887,  1.3989, -0.4783]])
torch.Size([5, 3])


### Addition

In [0]:
# syntax 1
y = torch.rand(5, 3)
print(x + y)
# syntax 2
print(torch.add(x, y))
# syntax 3: with the dimensions of result mentioned
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
# syntax 4: in-place addition
# adds x to y
y.add_(x)
print(y)
print(y.size())
print(x.size())

tensor([[ 1.1924,  0.5224,  0.8151],
        [ 1.8085,  0.6620,  1.7677],
        [ 1.0684,  0.3981, -1.8589],
        [ 0.4004,  1.5738, -2.0167],
        [-0.7332,  1.8730,  0.4619]])
tensor([[ 1.1924,  0.5224,  0.8151],
        [ 1.8085,  0.6620,  1.7677],
        [ 1.0684,  0.3981, -1.8589],
        [ 0.4004,  1.5738, -2.0167],
        [-0.7332,  1.8730,  0.4619]])
tensor([[ 1.1924,  0.5224,  0.8151],
        [ 1.8085,  0.6620,  1.7677],
        [ 1.0684,  0.3981, -1.8589],
        [ 0.4004,  1.5738, -2.0167],
        [-0.7332,  1.8730,  0.4619]])
tensor([[ 1.1924,  0.5224,  0.8151],
        [ 1.8085,  0.6620,  1.7677],
        [ 1.0684,  0.3981, -1.8589],
        [ 0.4004,  1.5738, -2.0167],
        [-0.7332,  1.8730,  0.4619]])
torch.Size([5, 3])
torch.Size([5, 3])


To carry out any mutation, use '_' after the method used

In [0]:
x=x.copy_(y)
print(x)
x=x.t_()
print(x)

tensor([[ 1.1924,  0.5224,  0.8151],
        [ 1.8085,  0.6620,  1.7677],
        [ 1.0684,  0.3981, -1.8589],
        [ 0.4004,  1.5738, -2.0167],
        [-0.7332,  1.8730,  0.4619]])
tensor([[ 1.1924,  1.8085,  1.0684,  0.4004, -0.7332],
        [ 0.5224,  0.6620,  0.3981,  1.5738,  1.8730],
        [ 0.8151,  1.7677, -1.8589, -2.0167,  0.4619]])


In [0]:
print(x[:, 1])
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x,y,z)

tensor([1.8085, 0.6620, 1.7677])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.1988, -0.1906, -0.8465,  0.6534],
        [ 2.2906, -0.5757,  0.1369,  2.4411],
        [ 0.8579,  0.8843, -0.0862, -0.6409],
        [ 0.7899,  1.5888,  1.4338, -0.5901]]) tensor([ 0.1988, -0.1906, -0.8465,  0.6534,  2.2906, -0.5757,  0.1369,  2.4411,
         0.8579,  0.8843, -0.0862, -0.6409,  0.7899,  1.5888,  1.4338, -0.5901]) tensor([[ 0.1988, -0.1906, -0.8465,  0.6534,  2.2906, -0.5757,  0.1369,  2.4411],
        [ 0.8579,  0.8843, -0.0862, -0.6409,  0.7899,  1.5888,  1.4338, -0.5901]])


In [0]:
x = torch.randn(1)
print(x)
print(x.item()) # .item() is used to get the number in the matrix

tensor([-0.3280])
-0.3279852867126465


### Converting a torch tensor to a numpy array


In [0]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy array to a Torch tensor

In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
class Employee:  
    id = 10;  
    name = "John"  
    def display (self):  
        print("ID: %d \nName: %s"%(self.id,self.name))  
emp = Employee()  
emp.display()  



ID: 10 
Name: John


In [0]:
import torch 
import numpy as np
data =np.array([1,2,3])
print(data)

t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

print(t1)
print(t2)
print(t3)
print(t4)

print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

# the differences between the tensor creations are that Tensor() is a constructor whereas the rest are factory creators
# the Tensor() and tensor() methods copy the data values into a tensor
# whereas the as_tensor() and from_numpy() methods share the data with the numpy and tensor packages
# hence, as_tensor() and from_numpy() are less intensive than the other two

# now the data in the numpy array is changed and the that in the tensor remains the same and the reason for the results in the below lines is explained in the lines above
data[0] = 0
data[1] = 0
data[2] = 0

print(t1, t1.dtype)
print(t2, t2.dtype)
print(t3, t3.dtype)
print(t4, t4.dtype)


[1 2 3]
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
torch.float32
torch.int64
torch.int64
torch.int64
tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3]) torch.int64
tensor([0, 0, 0]) torch.int64
tensor([0, 0, 0]) torch.int64


### Primary Operations in Pytorch
* Reshaping
* Element-wise 
* Reduction
* Access


In [0]:
# reshaping
trans1 = t1.reshape(1,9)
trans2 = t1.reshape(9,)
trans3 = t1.flatten()

RuntimeError: ignored

In [0]:
import torch
import numpy as np
# we have 4 axes to represent any input to a network(batch_size, no_of_colour_channels, width, height)

t1 = torch.tensor([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
t2 = torch.tensor([[2,2,2,2],[2,2,2,2],[2,2,2,2],[2,2,2,2]])
t3 = torch.tensor([[3,3,3,3],[3,3,3,3],[3,3,3,3],[3,3,3,3]])
t = torch.cat((t1,t2,t3), dim=1)
t_new = torch.stack((t1,t2,t3)) # to introduce a new dimension
print(t)
print(t_new)
print(t.shape)
print(t_new.shape)
# to introduce a colour channel
print(t_new.reshape(3,1,4,4))


tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3],
        [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3],
        [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3],
        [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])
torch.Size([4, 12])
torch.Size([3, 4, 4])
tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


In [0]:
t = t_new.reshape(3,1,4,4)
print(t.shape)
print(t[0])
print(t[0][0])
print(t[0][0][0])
print(t[0][0][0][0])

* Alternatives for flatten()


In [0]:
t.reshape(1,-1)[0]

In [0]:
t.reshape(48,)

In [0]:
t.reshape(-1)

In [0]:
t.view(t.numel())

In [0]:
t.flatten(start_dim=1).shape

In [0]:
t.flatten(start_dim=1) # to flatten across the image channel

In [0]:
t.flatten(start_dim=0).shape

In [0]:
t.flatten(start_dim=2).shape

In [0]:
t.flatten(start_dim=3).shape

In [0]:
### element-wise operations
t1 = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
t2 = torch.tensor([1,2,3])
print(t1+t2)
print(t1+np.broadcast_to(t2,t1.shape))


tensor([[2, 4, 6],
        [2, 4, 6],
        [2, 4, 6]])
tensor([[2, 4, 6],
        [2, 4, 6],
        [2, 4, 6]])


In [0]:
# reduction operations
print(t1.sum())
print(t1.numel())
print(t1.sum().numel())
print(t1.sum().numel()<t1.numel())

# since the sum() reduces the number of elements in the tensor to '1', we call it a reduction operation
t1 = torch.tensor(t1,dtype=torch.float32)
print(t1.mean())
print(t1.prod())
print(t1.std())

# reduction operations do not necessarily reduce to 1 number, they also reduce the tensors along a particular axis

print(t1.sum(dim=0))
print(t1.sum(dim=1))

tensor(18)
9
1
True
tensor(2.)
tensor(216.)
tensor(0.8660)
tensor([3., 6., 9.])
tensor([6., 6., 6.])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys


In [0]:
t2 = torch.tensor([[1,2,3],[7,8,9],[4,5,6]])
print(t1.dtype)
print(t2.dtype)
print(t1+t2)
print((t1+t2).dtype)
print((t1+t2).max())
print((t1+t2).max().item()) # to access only the number in the tensor
print((t1+t2).max(dim=0))
print((t1+t2).max(dim=1))
print((t1+t2).argmax()) # gives the position of the maximum number in the flattened vector of the tensor
print((t1+t2).argmax(dim=0))
print((t1+t2).argmax(dim=1))


torch.float32
torch.int64
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [ 5.,  7.,  9.]])
torch.float32
tensor(12.)
12.0
torch.return_types.max(
values=tensor([ 8., 10., 12.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([ 6., 12.,  9.]),
indices=tensor([2, 2, 2]))
tensor(5)
tensor([1, 1, 1])
tensor([2, 2, 2])
